def ingest_law(act_name, act_year, sections):
    laws = []
    for sec in sections:
        laws.append({
            "act_name": act_name,
            "act_year": act_year,
            "jurisdiction": "India",
            "section_or_article": sec["section"],
            "title": sec["title"],
            "full_text": sec["text"],
            "simple_explanation": "",   # generated by AI
            "keywords": [],
            "source_url": sec["url"]
        })
    return laws